### ISSUE TITLE
Issue running ecommerce in development mode

### ISSUE THREAD

**Issue by BbrSofiane** [overhangio/tutor-ecommerce#16]
**Bug description**

With the introduction of the [ecommerce mfe](https://github.com/edx/frontend-app-ecommerce), the development command:

`tutor dev runserver ecommerce`

Now starts the ecommerce mfe and without starting the e-commerce service.

**Solution**
 Change 
 
 ```
"MFE_APP": {
    "name": "ecommerce",
    "repository": "https://github.com/edx/frontend-app-ecommerce",
    "port": 1996,
},
```
        
to

```
"MFE_APP": {
    "name": "ecommercemfe",
    "repository": "https://github.com/edx/frontend-app-ecommerce",
    "port": 1996,
},
```

@overhangio/tutor-developers what do you think?

**Comment by regisb** [comment]
hmmmm good catch. Yes, this is a bug.

The problem with your suggested solution is that it will cause the ecommerce MFE to be served from http://appsyourlms.com/ecommercemfe -- which is not great. I mean: I like your solution, but I think we should try to find a different name. The ecommerce MFE is itself not very well named; after all the only thing it does is to display the user order history. So, could we simply use `"name": "orderhistory"`?

**Comment by BbrSofiane** [comment]
True I didn't think about the URL.

I thought about calling it `orderhistory` but it means that if there is more functionality added to it we might have to change the name. I'm making the assumption that since edX called the repo frontend-app-ecommerce they might add functionality beyond order history.

But I think for now orderhistory sounds good!

**Comment by regisb** [comment]
Maybe "orderhistory" is overly precise and we could go with simply "orders"?
