### ISSUE TITLE
server error message when I want to enter ecommerce

### ISSUE THREAD

**Issue by isaca0315** [overhangio/tutor-ecommerce#21]
server error message when I want to enter ecommerce
it doesn't load in oscar dashboard before I tried it but after update it doesn't work I get the following message could you please guide me on what could be the problem I am new using openedx

![Captura de Pantalla 2021-12-09 a la(s) 11 37 06 a  m](https://user-images.githubusercontent.com/31411458/145437805-1926708d-f3f9-482b-a258-cce3e66d542a.png)

**Comment by regisb** [comment]
Please don't use Github issues for feature requests or for support. Instead, you should create a new topic in the official Tutor forums: https://discuss.overhang.io.

The process for troubleshooting an existing installation and for contributing to the platform is described in the docs:
https://docs.tutor.overhang.io/troubleshooting.html
https://docs.tutor.overhang.io/tutor.html#contributing
