### ISSUE TITLE
ERROR 11 [django.security.DisallowedHost]

### ISSUE THREAD

**Issue by lpm0073** [overhangio/tutor-ecommerce#26]
I think i can tweak my deployment to get past this, but more generally, it looks like ALLOWED_HOSTS in ecommerce is not automatically being set.

The complete log error is:
ERROR 11 [django.security.DisallowedHost] /openedx/venv/lib/python3.8/site-packages/django/core/handlers/exception.py:99 - Invalid HTTP_HOST header: 'store.mooc.moocweb.com'. You may n eed to add 'store.mooc.moocweb.com' to ALLOWED_HOSTS.

**Comment by regisb** [comment]
Closing this for now. Please go to the forum: https://discuss.overhang.io/
(I'm prettty sure that your `ECOMMERCE_HOST` is incorrectly configured)
