### ISSUE TITLE
Do we have any stripe integration so far?

### ISSUE THREAD

**Issue by agusmakmun** [overhangio/tutor-ecommerce#30]
If didn't have, then what I can do to achieve this?

**Comment by diegoag64** [comment]
No stripe integration sadly, I believe there was some releases ago but I think it was dropped after MFEs were introduced

**Comment by agusmakmun** [comment]
I saw this tutorial, but not sure it will working or not: https://discuss.openedx.org/t/stripe-configuration-for-tutor-juniper-open-edx-release/4394/4

**Comment by regisb** [comment]
Please don't use Github issues for feature requests or for support. Instead, you should create a new topic in the official Open edX forum: https://discuss.openedx.org

The process for troubleshooting an existing installation and for contributing to the platform is described in the docs:
https://docs.tutor.overhang.io/troubleshooting.html
https://docs.tutor.overhang.io/tutor.html#contributing
