### ISSUE TITLE
tutor images build ecommerce - fails

### ISSUE THREAD

**Issue by Miu-Catalin** [overhangio/tutor-ecommerce#4]
Hi, I've tried to build ecommerce but it stops with an error related to  mysql-python

tutor, version 3.7.4
Ubuntu 18.04.3 LTS
docker-compose version 1.17.1

[error.log](https://github.com/overhangio/tutor-ecommerce/files/3875787/error.log)

**Comment by regisb** [comment]
Hi @Miu-Catalin! You seem to have multiple errors going on at the same time here. First of all, what version of docker are you running? You can get that version with `docker --version`.

**Comment by Miu-Catalin** [comment]
Hi @regisb,

`Docker version 19.03.4, build 9013bf583a`

**Comment by regisb** [comment]
How did you install tutor? (aka: from binary/pip/git clone)

**Comment by Miu-Catalin** [comment]
binary

**Comment by regisb** [comment]
Thanks for reporting this @Miu-Catalin! I do not quite understand why this bug did not occur before, but the fix will be available in the next release (v0.1.6) which should be available in a couple minutes.
