### ISSUE TITLE
Ecommerce configuration issue - Publishing Course Modes to LMS fails.

### ISSUE THREAD

**Issue by Jacatove** [overhangio/tutor-ecommerce#40]
When creating a course in eCommerce using Tutor 15, the procedure failed because it was using these variables to perform the API call [SOCIAL_AUTH_EDX_OAUTH2_URL_ROOT and BACKEND_SERVICE_EDX_OAUTH2_PROVIDER_URL](https://github.com/overhangio/tutor-ecommerce/blob/db450305c1fa3c192580757b4f1916cdeef4b23c/tutorecommerce/templates/ecommerce/apps/ecommerce/settings/partials/common.py#L43-L46). There is no way to define them using tutor-ecommerce, so I had to manually set the appropriate value.

**Comment by regisb** [comment]
I realize that I'm very late in replying, but do you have some stacktrace or logs to explain what exactly is failing?

**Comment by regisb** [comment]
Hey @Jacatove, we are going to close this now. Feel free to re-open if you think the issue still occurs in v17.0.0.
