### ISSUE TITLE
Error when running tutor local launch after plugin enabled

### ISSUE THREAD

**Issue by johnny77221** [overhangio/tutor-ecommerce#59]
I am setting up using tutor, version 16.1.7
with last two releases(16.0.1 & 16.0.2) of tutor-ecommerce, I encountered error when running tutor local launch
it shows:

Running init task in ecommerce
Error: Missing configuration value: 'tuple object' has no attribute 'name'

and the script exits and the site will show server error after login

**Comment by regisb** [comment]
I have reproduced the issue here: https://github.com/overhangio/openedx-release-demo/actions/runs/7164720697/job/19507131728

Working on a fix right now.

**Comment by Faraz32123** [comment]
@regisb there's also another issue reported in this github issue that the 500 server error was also occurring and i reproduced the same, 
I had also done the same fix that u have done and some extra fix for 500 server error.

**Comment by Faraz32123** [comment]
I'll close the issue once i create/merge a PR for the 500 internet server error.
