### ISSUE TITLE
There was an error building the open edx project using 'tutor local quickstart'

### ISSUE THREAD

**Issue by HertZPY** [overhangio/tutor-ecommerce#6]
Install the [tutor-ecommerce](https://pypi.org/project/tutor-ecommerce/) plug-in and install it into the build open edx project environment using 'tutor local quickstart' as described in the document. What configuration did I neglect or what steps did I miss to cause the error?
The screenshot of the question is as follows:

![TIM图片20200331184542](https://user-images.githubusercontent.com/51052759/78109666-30b58c80-73e9-11ea-9e8d-b06929a775a7.png)

**Comment by ak00001** [comment]
Did you install the Discovery plugin first?

**Comment by HertZPY** [comment]
@ak00001 yes
![TIM图片20200403094310](https://user-images.githubusercontent.com/51052759/78315472-9f5f2b00-754c-11ea-9700-4bb2adbfc333.png)

**Comment by HertZPY** [comment]
@ak00001 

![TIM图片20200403094310](https://user-images.githubusercontent.com/51052759/78316988-9a9c7600-7550-11ea-8efe-ca336b75a93e.png)

**Comment by HertZPY** [comment]
The operating system：ubuntu18.04
tutor version：3.11.6
steps：

```
tutor plugins list
```

```
pip3 install tutor-ecommerce
```

```
tutor plugins enable discovery ecommerce
```

```
tutor local quickstart
```

The screenshots：

![TIM图片20200403094310](https://user-images.githubusercontent.com/51052759/78331409-7ef79680-7575-11ea-8402-853b6204b2de.png)

![TIM图片20200403143510](https://user-images.githubusercontent.com/51052759/78331427-86b73b00-7575-11ea-9d01-c53ad9c94ea5.png)

![TIM图片20200403143900](https://user-images.githubusercontent.com/51052759/78331730-31c7f480-7576-11ea-870f-fe8a4c2290a6.png)

![TIM图片20200403144130](https://user-images.githubusercontent.com/51052759/78331744-37253f00-7576-11ea-8905-72a982474aa8.png)

**Comment by HertZPY** [comment]
The problem has been resolved and the DISCOVERY_HOST field needs to be added to the configuration file and cannot be set to 'discovery.localhost'；I think this needs to be indicated in the installation documentation，Thank you。

**Comment by regisb** [comment]
The problem stems from the fact that you set LMS_HOST="localhost". You should not be doing that.
