### ISSUE TITLE
Cannot create course seats

### ISSUE THREAD

**Issue by johnny77221** [overhangio/tutor-ecommerce#63]
I followed instructions here:
https://edx-ecommerce.readthedocs.io/en/latest/create_products/create_course_seats.html#create-course-seats

when creating a new course, it comes out with error says please fill in all required fields even I did
I tried on "Verified and Audit" and "Professional Education" but no luck on this
<img width="1428" alt="error_required" src="https://github.com/overhangio/tutor-ecommerce/assets/101882/ba66d500-2297-4bc7-bd0b-e26c1dc68bb7">

do you have any clue on this?

**Comment by Danyal-Faheem** [comment]
Hi @johnny77221, I tried to reproduce this error on Tutor Quince but I was unable to do so. Can you provide more details regarding your tutor such as: 

- Tutor version
- Ecommerce logs (You can run `tutor local logs ecommerce` for this, [tutor logs docs](https://docs.tutor.edly.io/reference/cli/local.html#tutor-local-logs) for reference)
- Any specific data or configuration you have applied to tutor, ecommerce or discovery.

**Comment by johnny77221** [comment]
Hi, this happens on tutor v16 and 17
and after a refresh of page, it went well so I am not able to reproduce right now(on both 16 and 17 version)
I guess there's some kind of problem at first install but I don't have prove on it

here's log for the tutor local logs ecommerce
the cyber source error happened was because I didn't; delete config, after I deleted it, it works fine
[eclog.txt](https://github.com/overhangio/tutor-ecommerce/files/13896023/eclog.txt)

please refer if this helps

thank you for your help

**Comment by Danyal-Faheem** [comment]
As the error can't be reproduced, I'm going to close this issue now.
