### ISSUE TITLE
tutor.py configuration path is wrong when start ecommerce on k8s

### ISSUE THREAD

**Issue by pcliupc** [overhangio/tutor-ecommerce#8]
Meets error when run master branch for k8s environment (v1.14)
seems that tutorecommerce/templates/ecommerce/apps/tutor.py should be put under tutorecommerce/templates/ecommerce/apps/settings.

**Comment by pcliupc** [comment]
Another issue of k8s deployment is ecommerce_worker cannot be started, seems that k8s does not allow '_' in deployment and configMap name. 
May change deployment 'ecommerce_worker' to 'ecommerce-worker'?

**Comment by regisb** [comment]
Hi @pcliupc! Thanks for the report. Both issues should be fixed in the latest release (v0.1.0). Can you please confirm?

**Comment by pcliupc** [comment]
@regisb thanks for fixing the two issues, works in my dev env.
